In [1]:
import pandas as pd

In [2]:
data={"Name:[a,b,c]","age:[20,30,45]"}
data

{'Name:[a,b,c]', 'age:[20,30,45]'}

In [3]:
df=pd.DataFrame(data)
df

                0
0    Name:[a,b,c]
1  age:[20,30,45]

In [4]:
df=pd.read_csv("employee_salary_dataset.csv")
df

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381
11,12,Employee_12,IT,4,Master,49,Female,Hyderabad,104909
12,13,Employee_13,Operations,2,Master,23,Female,Hyderabad,72333
13,14,Employee_14,Finance,6,Bachelor,27,Male,Delhi,28436
14,15,Employee_15,Marketing,10,PhD,49,Female,Mumbai,99290
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213
16,17,Employee_17,Marketing,18,Master,41,Female,Hyderabad,30895
17,18,Employee_18,Operations,12,PhD,51,Female,Chennai,44738
18,19,Employee_19,HR,2,PhD,32,Male,Chennai,55746
19,20,Employee_20,Marketing,10,Bachelor,49,Male,Bangalore,74377
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404
21,22,Employee_22,Operations,14,Master,54,Female,Delhi,79045
22,23,Employee_23,Marketing,16,High School,22,Male,Bangalore,122888
23,24,Employee_24,HR,15,Master,48,Male,Bangalore,64790
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455
25,26,Employee_26,IT,14,Master,24,Male,Hyderabad,30600
26,27,Employee_27,IT,8,Bachelor,27,Female,Delhi,119660
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179
28,29,Employee_29,Marketing,13,High School,48,Male,Bangalore,65764
29,30,Employee_30,Marketing,18,High School,30,Male,Delhi,99543
30,31,Employee_31,IT,15,Bachelor,54,Female,Hyderabad,70714
31,32,Employee_32,Marketing,13,Master,45,Female,Hyderabad,81835
32,33,Employee_33,Marketing,9,Master,36,Male,Bangalore,127946
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616
34,35,Employee_35,IT,13,Master,53,Male,Bangalore,130983
35,36,Employee_36,Operations,1,Master,45,Female,Delhi,98744
36,37,Employee_37,IT,7,High School,33,Male,Chennai,81491
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123
38,39,Employee_39,HR,1,Master,24,Male,Mumbai,43589
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484
40,41,Employee_41,Marketing,8,Bachelor,23,Female,Bangalore,107989
41,42,Employee_42,HR,11,PhD,23,Male,Chennai,61212
42,43,Employee_43,Marketing,19,High School,49,Female,Delhi,68525
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202
44,45,Employee_45,Finance,8,Master,53,Male,Delhi,57635
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752

In [5]:
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450

In [7]:
df.tail()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752

In [8]:
df.columns

Index(['EmployeeID', 'Name', 'Department', 'Experience_Years',
       'Education_Level', 'Age', 'Gender', 'City', 'Monthly_Salary'],
      dtype='object')

In [12]:
df.dtypes

EmployeeID           int64
Name                object
Department          object
Experience_Years     int64
Education_Level     object
Age                  int64
Gender              object
City                object
Monthly_Salary       int64
dtype: object

In [13]:
df.describe()

       EmployeeID  Experience_Years        Age  Monthly_Salary
count    50.00000         50.000000  50.000000         50.0000
mean     25.50000          9.900000  39.760000      82288.8000
std      14.57738          5.349995  11.539745      33521.4379
min       1.00000          1.000000  22.000000      28420.0000
25%      13.25000          5.250000  28.250000      59424.0000
50%      25.50000         10.000000  43.500000      73890.5000
75%      37.75000         14.750000  49.000000     107219.0000
max      50.00000         19.000000  57.000000     149123.0000

In [14]:
#select single column multiple columns and rows using index

In [15]:
import pandas as pd

In [17]:
df=pd.read_csv("employee_salary_dataset.csv")
print(df["Age"])
print(df[["Name","Age"]])
print(df.iloc[0:5])

0     53
1     25
2     51
3     44
4     36
5     50
6     57
7     34
8     53
9     28
10    43
11    49
12    23
13    27
14    49
15    49
16    41
17    51
18    32
19    49
20    46
21    54
22    22
23    48
24    34
25    24
26    27
27    29
28    48
29    30
30    54
31    45
32    36
33    53
34    53
35    45
36    33
37    23
38    24
39    38
40    23
41    23
42    49
43    44
44    53
45    54
46    22
47    40
48    23
49    47
Name: Age, dtype: int64
           Name  Age
0    Employee_1   53
1    Employee_2   25
2    Employee_3   51
3    Employee_4   44
4    Employee_5   36
5    Employee_6   50
6    Employee_7   57
7    Employee_8   34
8    Employee_9   53
9   Employee_10   28
10  Employee_11   43
11  Employee_12   49
12  Employee_13   23
13  Employee_14   27
14  Employee_15   49
15  Employee_16   49
16  Employee_17   41
17  Employee_18   51
18  Employee_19   32
19  Employee_20   49
20  Employee_21   46
21  Employee_22   54
22  Employee_23   22
23  Employee_24   48
24  Employee_25   34
25  Employee_26   24
26  Employee_27   27
27  Employee_28   29
28  Employee_29   48
29  Employee_30   30
30  Employee_31   54
31  Employee_32   45
32  Employee_33   36
33  Employee_34   53
34  Employee_35   53
35  Employee_36   45
36  Employee_37   33
37  Employee_38   23
38  Employee_39   24
39  Employee_40   38
40  Employee_41   23
41  Employee_42   23
42  Employee_43   49
43  Employee_44   44
44  Employee_45   53
45  Employee_46   54
46  Employee_47   22
47  Employee_48   40
48  Employee_49   23
49  Employee_50   47
   EmployeeID        Name  Department  Experience_Years Education_Level  Age  \
0           1  Employee_1   Marketing                15          Master   53
1           2  Employee_2  Operations                 7        Bachelor   25
2           3  Employee_3          IT                12     High School   51
3           4  Employee_4  Operations                 8             PhD   44
4           5  Employee_5  Operations                15          Master   36

   Gender       City  Monthly_Salary
0  Female      Delhi          111416
1  Female  Bangalore           95271
2  Female  Hyderabad           69064
3    Male      Delhi           95091
4  Female      Delhi          132450

In [19]:
print(df[df["Age"]>25])
print(df[df["Monthly_Salary"]<50000])

    EmployeeID         Name  Department  Experience_Years Education_Level  \
0            1   Employee_1   Marketing                15          Master
2            3   Employee_3          IT                12     High School
3            4   Employee_4  Operations                 8             PhD
4            5   Employee_5  Operations                15          Master
5            6   Employee_6     Finance                 3     High School
6            7   Employee_7          IT                14             PhD
7            8   Employee_8          IT                17             PhD
8            9   Employee_9          IT                 4        Bachelor
9           10  Employee_10  Operations                18     High School
10          11  Employee_11   Marketing                 8             PhD
11          12  Employee_12          IT                 4          Master
13          14  Employee_14     Finance                 6        Bachelor
14          15  Employee_15   Marketing                10             PhD
15          16  Employee_16     Finance                 4     High School
16          17  Employee_17   Marketing                18          Master
17          18  Employee_18  Operations                12             PhD
18          19  Employee_19          HR                 2             PhD
19          20  Employee_20   Marketing                10        Bachelor
20          21  Employee_21     Finance                 4          Master
21          22  Employee_22  Operations                14          Master
23          24  Employee_24          HR                15          Master
24          25  Employee_25          HR                 8     High School
26          27  Employee_27          IT                 8        Bachelor
27          28  Employee_28     Finance                16          Master
28          29  Employee_29   Marketing                13     High School
29          30  Employee_30   Marketing                18     High School
30          31  Employee_31          IT                15        Bachelor
31          32  Employee_32   Marketing                13          Master
32          33  Employee_33   Marketing                 9          Master
33          34  Employee_34          HR                15        Bachelor
34          35  Employee_35          IT                13          Master
35          36  Employee_36  Operations                 1          Master
36          37  Employee_37          IT                 7     High School
39          40  Employee_40     Finance                12        Bachelor
42          43  Employee_43   Marketing                19     High School
43          44  Employee_44     Finance                17          Master
44          45  Employee_45     Finance                 8          Master
45          46  Employee_46          HR                 3             PhD
47          48  Employee_48  Operations                 1     High School
49          50  Employee_50   Marketing                10     High School

    Age  Gender       City  Monthly_Salary
0    53  Female      Delhi          111416
2    51  Female  Hyderabad           69064
3    44    Male      Delhi           95091
4    36  Female      Delhi          132450
5    50    Male     Mumbai           65818
6    57    Male     Mumbai           70525
7    34  Female  Bangalore           44830
8    53    Male  Hyderabad           42429
9    28    Male     Mumbai           31893
10   43    Male      Delhi          141381
11   49  Female  Hyderabad          104909
13   27    Male      Delhi           28436
14   49  Female     Mumbai           99290
15   49  Female      Delhi          101213
16   41  Female  Hyderabad           30895
17   51  Female    Chennai           44738
18   32    Male    Chennai           55746
19   49    Male  Bangalore           74377
20   46  Female      Delhi           73404
21   54  Female      Delhi           79045
23   48    Male  Bangalore           64790
24   34  Female  Bangalore          132455
26   27  Female      Delhi          119660
27   29  Female  Hyderabad          118179
28   48    Male  Bangalore           65764
29   30    Male      Delhi           99543
30   54  Female  Hyderabad           70714
31   45  Female  Hyderabad           81835
32   36    Male  Bangalore          127946
33   53  Female      Delhi          134616
34   53    Male  Bangalore          130983
35   45  Female      Delhi           98744
36   33    Male    Chennai           81491
39   38  Female     Mumbai           68484
42   49  Female      Delhi           68525
43   44    Male  Hyderabad           72202
44   53    Male      Delhi           57635
45   54  Female  Hyderabad           88208
47   40    Male    Chennai           43711
49   47  Female  Bangalore          121752
    EmployeeID         Name  Department  Experience_Years Education_Level  \
7            8   Employee_8          IT                17             PhD
8            9   Employee_9          IT                 4        Bachelor
9           10  Employee_10  Operations                18     High School
13          14  Employee_14     Finance                 6        Bachelor
16          17  Employee_17   Marketing                18          Master
17          18  Employee_18  Operations                12             PhD
25          26  Employee_26          IT                14          Master
38          39  Employee_39          HR                 1          Master
47          48  Employee_48  Operations                 1     High School
48          49  Employee_49     Finance                 5             PhD

    Age  Gender       City  Monthly_Salary
7    34  Female  Bangalore           44830
8    53    Male  Hyderabad           42429
9    28    Male     Mumbai           31893
13   27    Male      Delhi           28436
16   41  Female  Hyderabad           30895
17   51  Female    Chennai           44738
25   24    Male  Hyderabad           30600
38   24    Male     Mumbai           43589
47   40    Male    Chennai           43711
48   23  Female  Hyderabad           28420

In [20]:
print(df.sort_values(by="Age"))

    EmployeeID         Name  Department  Experience_Years Education_Level  \
22          23  Employee_23   Marketing                16     High School
46          47  Employee_47     Finance                 3          Master
41          42  Employee_42          HR                11             PhD
12          13  Employee_13  Operations                 2          Master
40          41  Employee_41   Marketing                 8        Bachelor
48          49  Employee_49     Finance                 5             PhD
37          38  Employee_38  Operations                 9          Master
38          39  Employee_39          HR                 1          Master
25          26  Employee_26          IT                14          Master
1            2   Employee_2  Operations                 7        Bachelor
26          27  Employee_27          IT                 8        Bachelor
13          14  Employee_14     Finance                 6        Bachelor
9           10  Employee_10  Operations                18     High School
27          28  Employee_28     Finance                16          Master
29          30  Employee_30   Marketing                18     High School
18          19  Employee_19          HR                 2             PhD
36          37  Employee_37          IT                 7     High School
24          25  Employee_25          HR                 8     High School
7            8   Employee_8          IT                17             PhD
32          33  Employee_33   Marketing                 9          Master
4            5   Employee_5  Operations                15          Master
39          40  Employee_40     Finance                12        Bachelor
47          48  Employee_48  Operations                 1     High School
16          17  Employee_17   Marketing                18          Master
10          11  Employee_11   Marketing                 8             PhD
43          44  Employee_44     Finance                17          Master
3            4   Employee_4  Operations                 8             PhD
31          32  Employee_32   Marketing                13          Master
35          36  Employee_36  Operations                 1          Master
20          21  Employee_21     Finance                 4          Master
49          50  Employee_50   Marketing                10     High School
28          29  Employee_29   Marketing                13     High School
23          24  Employee_24          HR                15          Master
42          43  Employee_43   Marketing                19     High School
14          15  Employee_15   Marketing                10             PhD
15          16  Employee_16     Finance                 4     High School
11          12  Employee_12          IT                 4          Master
19          20  Employee_20   Marketing                10        Bachelor
5            6   Employee_6     Finance                 3     High School
17          18  Employee_18  Operations                12             PhD
2            3   Employee_3          IT                12     High School
34          35  Employee_35          IT                13          Master
8            9   Employee_9          IT                 4        Bachelor
33          34  Employee_34          HR                15        Bachelor
44          45  Employee_45     Finance                 8          Master
0            1   Employee_1   Marketing                15          Master
21          22  Employee_22  Operations                14          Master
30          31  Employee_31          IT                15        Bachelor
45          46  Employee_46          HR                 3             PhD
6            7   Employee_7          IT                14             PhD

    Age  Gender       City  Monthly_Salary
22   22    Male  Bangalore          122888
46   22  Female      Delhi           58828
41   23    Male    Chennai           61212
12   23  Female  Hyderabad           72333
40   23  Female  Bangalore          107989
48   23  Female  Hyderabad           28420
37   23    Male     Mumbai          149123
38   24    Male     Mumbai           43589
25   24    Male  Hyderabad           30600
1    25  Female  Bangalore           95271
26   27  Female      Delhi          119660
13   27    Male      Delhi           28436
9    28    Male     Mumbai           31893
27   29  Female  Hyderabad          118179
29   30    Male      Delhi           99543
18   32    Male    Chennai           55746
36   33    Male    Chennai           81491
24   34  Female  Bangalore          132455
7    34  Female  Bangalore           44830
32   36    Male  Bangalore          127946
4    36  Female      Delhi          132450
39   38  Female     Mumbai           68484
47   40    Male    Chennai           43711
16   41  Female  Hyderabad           30895
10   43    Male      Delhi          141381
43   44    Male  Hyderabad           72202
3    44    Male      Delhi           95091
31   45  Female  Hyderabad           81835
35   45  Female      Delhi           98744
20   46  Female      Delhi           73404
49   47  Female  Bangalore          121752
28   48    Male  Bangalore           65764
23   48    Male  Bangalore           64790
42   49  Female      Delhi           68525
14   49  Female     Mumbai           99290
15   49  Female      Delhi          101213
11   49  Female  Hyderabad          104909
19   49    Male  Bangalore           74377
5    50    Male     Mumbai           65818
17   51  Female    Chennai           44738
2    51  Female  Hyderabad           69064
34   53    Male  Bangalore          130983
8    53    Male  Hyderabad           42429
33   53  Female      Delhi          134616
44   53    Male      Delhi           57635
0    53  Female      Delhi          111416
21   54  Female      Delhi           79045
30   54  Female  Hyderabad           70714
45   54  Female  Hyderabad           88208
6    57    Male     Mumbai           70525

In [21]:
print(df.sort_values(by=["Age","Monthly_Salary"]))

    EmployeeID         Name  Department  Experience_Years Education_Level  \
46          47  Employee_47     Finance                 3          Master
22          23  Employee_23   Marketing                16     High School
48          49  Employee_49     Finance                 5             PhD
41          42  Employee_42          HR                11             PhD
12          13  Employee_13  Operations                 2          Master
40          41  Employee_41   Marketing                 8        Bachelor
37          38  Employee_38  Operations                 9          Master
25          26  Employee_26          IT                14          Master
38          39  Employee_39          HR                 1          Master
1            2   Employee_2  Operations                 7        Bachelor
13          14  Employee_14     Finance                 6        Bachelor
26          27  Employee_27          IT                 8        Bachelor
9           10  Employee_10  Operations                18     High School
27          28  Employee_28     Finance                16          Master
29          30  Employee_30   Marketing                18     High School
18          19  Employee_19          HR                 2             PhD
36          37  Employee_37          IT                 7     High School
7            8   Employee_8          IT                17             PhD
24          25  Employee_25          HR                 8     High School
32          33  Employee_33   Marketing                 9          Master
4            5   Employee_5  Operations                15          Master
39          40  Employee_40     Finance                12        Bachelor
47          48  Employee_48  Operations                 1     High School
16          17  Employee_17   Marketing                18          Master
10          11  Employee_11   Marketing                 8             PhD
43          44  Employee_44     Finance                17          Master
3            4   Employee_4  Operations                 8             PhD
31          32  Employee_32   Marketing                13          Master
35          36  Employee_36  Operations                 1          Master
20          21  Employee_21     Finance                 4          Master
49          50  Employee_50   Marketing                10     High School
23          24  Employee_24          HR                15          Master
28          29  Employee_29   Marketing                13     High School
42          43  Employee_43   Marketing                19     High School
19          20  Employee_20   Marketing                10        Bachelor
14          15  Employee_15   Marketing                10             PhD
15          16  Employee_16     Finance                 4     High School
11          12  Employee_12          IT                 4          Master
5            6   Employee_6     Finance                 3     High School
17          18  Employee_18  Operations                12             PhD
2            3   Employee_3          IT                12     High School
8            9   Employee_9          IT                 4        Bachelor
44          45  Employee_45     Finance                 8          Master
0            1   Employee_1   Marketing                15          Master
34          35  Employee_35          IT                13          Master
33          34  Employee_34          HR                15        Bachelor
30          31  Employee_31          IT                15        Bachelor
21          22  Employee_22  Operations                14          Master
45          46  Employee_46          HR                 3             PhD
6            7   Employee_7          IT                14             PhD

    Age  Gender       City  Monthly_Salary
46   22  Female      Delhi           58828
22   22    Male  Bangalore          122888
48   23  Female  Hyderabad           28420
41   23    Male    Chennai           61212
12   23  Female  Hyderabad           72333
40   23  Female  Bangalore          107989
37   23    Male     Mumbai          149123
25   24    Male  Hyderabad           30600
38   24    Male     Mumbai           43589
1    25  Female  Bangalore           95271
13   27    Male      Delhi           28436
26   27  Female      Delhi          119660
9    28    Male     Mumbai           31893
27   29  Female  Hyderabad          118179
29   30    Male      Delhi           99543
18   32    Male    Chennai           55746
36   33    Male    Chennai           81491
7    34  Female  Bangalore           44830
24   34  Female  Bangalore          132455
32   36    Male  Bangalore          127946
4    36  Female      Delhi          132450
39   38  Female     Mumbai           68484
47   40    Male    Chennai           43711
16   41  Female  Hyderabad           30895
10   43    Male      Delhi          141381
43   44    Male  Hyderabad           72202
3    44    Male      Delhi           95091
31   45  Female  Hyderabad           81835
35   45  Female      Delhi           98744
20   46  Female      Delhi           73404
49   47  Female  Bangalore          121752
23   48    Male  Bangalore           64790
28   48    Male  Bangalore           65764
42   49  Female      Delhi           68525
19   49    Male  Bangalore           74377
14   49  Female     Mumbai           99290
15   49  Female      Delhi          101213
11   49  Female  Hyderabad          104909
5    50    Male     Mumbai           65818
17   51  Female    Chennai           44738
2    51  Female  Hyderabad           69064
8    53    Male  Hyderabad           42429
44   53    Male      Delhi           57635
0    53  Female      Delhi          111416
34   53    Male  Bangalore          130983
33   53  Female      Delhi          134616
30   54  Female  Hyderabad           70714
21   54  Female      Delhi           79045
45   54  Female  Hyderabad           88208
6    57    Male     Mumbai           70525

In [25]:
df=pd.read_csv("employee_salary_dataset.csv")
df.to_csv("job_salary_prediction_dataset.csv",index=False)
print("file saved successfully")

file saved successfully