In [1]:
import pandas as pd

In [25]:
f=pd.read_csv("fullGas.csv")
f

,Make,Model,Body,Mileage_km,Price,Year,Country,Condition,Fuel_Type,Fuel_Consumption_l,...,Cylinders,Seats,Doors,Color,Upholstery,Full_Service_History,Non_Smoker_Vehicle,Previous_Owners,Seller,Image_url
0,Abarth,595,Compact,98000,16900,2020.0,IT,Used,Gasoline,6.7,...,4.0,4.0,3.0,White,Full leather,False,False,NaN,Dealer,https://prod.pictures.autoscout24.net/listing-...
1,Abarth,595,Sedan,91500,12500,2017.0,IT,Used,Gasoline,6.0,...,4.0,4.0,3.0,Grey,Full leather,False,True,4.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
2,Abarth,595,Compact,40000,17990,2015.0,IT,Used,Gasoline,6.5,...,4.0,4.0,3.0,Bronze,Full leather,True,True,1.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
3,Abarth,500,Compact,133000,9300,2008.0,IT,Used,Gasoline,6.5,...,4.0,4.0,3.0,Black,Cloth,True,True,2.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
4,Abarth,595,Compact,61019,14990,2021.0,BE,Used,Gasoline,NaN,...,4.0,4.0,3.0,Yellow,Part leather,True,True,1.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40489,Volvo,V60 Cross Country,Station wagon,73627,32990,2023.0,DE,Used,Diesel,NaN,...,NaN,5.0,5.0,Grey,Part leather,True,True,1.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
40490,Volvo,XC60,Off-Road/Pick-up,93671,26990,2020.0,IT,Used,Electric/Diesel,NaN,...,4.0,5.0,5.0,Grey,Cloth,False,False,NaN,Dealer,https://prod.pictures.autoscout24.net/listing-...
40491,Volvo,V90,Station wagon,60200,32490,2020.0,DE,Used,Gasoline,NaN,...,4.0,5.0,5.0,Black,Full leather,True,True,2.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
40492,Volvo,XC40,Off-Road/Pick-up,49088,29450,2022.0,NL,Used,Electric/Gasoline,NaN,...,3.0,5.0,5.0,Black,Cloth,True,False,NaN,Dealer,https://prod.pictures.autoscout24.net/listing-...
40493,Volvo,XC90,Off-Road/Pick-up,124750,43990,2022.0,DE,Used,Diesel,NaN,...,4.0,5.0,5.0,Grey,Full leather,True,True,2.0,Dealer,https://prod.pictures.autoscout24.net/listing-...

In [26]:
f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40494 entries, 0 to 40493
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Make                  40494 non-null  object
 1   Model                 40273 non-null  object
 2   Body                  40493 non-null  object
 3   Mileage_km            40494 non-null  int64
 4   Price                 40494 non-null  int64
 5   Year                  38799 non-null  float64
 6   Country               37902 non-null  object
 7   Condition             40494 non-null  object
 8   Fuel_Type             40465 non-null  object
 9   Fuel_Consumption_l    12773 non-null  float64
 10  Drivetrain            31860 non-null  object
 11  Gearbox               40014 non-null  object
 12  Gears                 25115 non-null  float64
 13  Power_hp              40494 non-null  int64
 14  Engine_Size_cc        34564 non-null  float64
 15  Cylinders             30332 non-null  float64
 16  Seats                 38697 non-null  float64
 17  Doors                 39517 non-null  float64
 18  Color                 37919 non-null  object
 19  Upholstery            33222 non-null  object
 20  Full_Service_History  40494 non-null  bool
 21  Non_Smoker_Vehicle    40494 non-null  bool
 22  Previous_Owners       22271 non-null  float64
 23  Seller                40344 non-null  object
 24  Image_url             40494 non-null  object
dtypes: bool(2), float64(8), int64(3), object(12)
memory usage: 7.2+ MB

In [27]:
f=f.drop("Image_url",axis=1)
f

,Make,Model,Body,Mileage_km,Price,Year,Country,Condition,Fuel_Type,Fuel_Consumption_l,...,Engine_Size_cc,Cylinders,Seats,Doors,Color,Upholstery,Full_Service_History,Non_Smoker_Vehicle,Previous_Owners,Seller
0,Abarth,595,Compact,98000,16900,2020.0,IT,Used,Gasoline,6.7,...,1368.0,4.0,4.0,3.0,White,Full leather,False,False,NaN,Dealer
1,Abarth,595,Sedan,91500,12500,2017.0,IT,Used,Gasoline,6.0,...,1368.0,4.0,4.0,3.0,Grey,Full leather,False,True,4.0,Dealer
2,Abarth,595,Compact,40000,17990,2015.0,IT,Used,Gasoline,6.5,...,1368.0,4.0,4.0,3.0,Bronze,Full leather,True,True,1.0,Dealer
3,Abarth,500,Compact,133000,9300,2008.0,IT,Used,Gasoline,6.5,...,1368.0,4.0,4.0,3.0,Black,Cloth,True,True,2.0,Dealer
4,Abarth,595,Compact,61019,14990,2021.0,BE,Used,Gasoline,NaN,...,1368.0,4.0,4.0,3.0,Yellow,Part leather,True,True,1.0,Dealer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40489,Volvo,V60 Cross Country,Station wagon,73627,32990,2023.0,DE,Used,Diesel,NaN,...,1969.0,NaN,5.0,5.0,Grey,Part leather,True,True,1.0,Dealer
40490,Volvo,XC60,Off-Road/Pick-up,93671,26990,2020.0,IT,Used,Electric/Diesel,NaN,...,1969.0,4.0,5.0,5.0,Grey,Cloth,False,False,NaN,Dealer
40491,Volvo,V90,Station wagon,60200,32490,2020.0,DE,Used,Gasoline,NaN,...,1969.0,4.0,5.0,5.0,Black,Full leather,True,True,2.0,Dealer
40492,Volvo,XC40,Off-Road/Pick-up,49088,29450,2022.0,NL,Used,Electric/Gasoline,NaN,...,1477.0,3.0,5.0,5.0,Black,Cloth,True,False,NaN,Dealer
40493,Volvo,XC90,Off-Road/Pick-up,124750,43990,2022.0,DE,Used,Diesel,NaN,...,1969.0,4.0,5.0,5.0,Grey,Full leather,True,True,2.0,Dealer

In [28]:
f.columns

Index(['Make', 'Model', 'Body', 'Mileage_km', 'Price', 'Year', 'Country',
       'Condition', 'Fuel_Type', 'Fuel_Consumption_l', 'Drivetrain', 'Gearbox',
       'Gears', 'Power_hp', 'Engine_Size_cc', 'Cylinders', 'Seats', 'Doors',
       'Color', 'Upholstery', 'Full_Service_History', 'Non_Smoker_Vehicle',
       'Previous_Owners', 'Seller'],
      dtype='object')

In [29]:
f.isnull().sum()

Make                        0
Model                     221
Body                        1
Mileage_km                  0
Price                       0
Year                     1695
Country                  2592
Condition                   0
Fuel_Type                  29
Fuel_Consumption_l      27721
Drivetrain               8634
Gearbox                   480
Gears                   15379
Power_hp                    0
Engine_Size_cc           5930
Cylinders               10162
Seats                    1797
Doors                     977
Color                    2575
Upholstery               7272
Full_Service_History        0
Non_Smoker_Vehicle          0
Previous_Owners         18223
Seller                    150
dtype: int64

In [30]:
f["Car_age"]=2026-f["Year"]
f["Car_age"]

0         6.0
1         9.0
2        11.0
3        18.0
4         5.0
         ...
40489     3.0
40490     6.0
40491     6.0
40492     4.0
40493     4.0
Name: Car_age, Length: 40494, dtype: float64

In [31]:
f["price_perkm"] = f["Price"]/(f["Mileage_km"]+1)
f["price_perkm"]

0        0.172447
1        0.136611
2        0.449739
3        0.069924
4        0.245657
           ...
40489    0.448063
40490    0.288133
40491    0.539692
40492    0.599931
40493    0.352622
Name: price_perkm, Length: 40494, dtype: float64

In [32]:
fn = f.select_dtypes(["int64","float64"]).columns
fn

Index(['Mileage_km', 'Price', 'Year', 'Fuel_Consumption_l', 'Gears',
       'Power_hp', 'Engine_Size_cc', 'Cylinders', 'Seats', 'Doors',
       'Previous_Owners', 'Car_age', 'price_perkm'],
      dtype='object')

In [33]:
f[fn] = f[fn].fillna(f[fn].median())
f[fn].isnull().sum()

Mileage_km            0
Price                 0
Year                  0
Fuel_Consumption_l    0
Gears                 0
Power_hp              0
Engine_Size_cc        0
Cylinders             0
Seats                 0
Doors                 0
Previous_Owners       0
Car_age               0
price_perkm           0
dtype: int64

In [35]:
f1=f.select_dtypes(["object"]).columns
f1

Index(['Make', 'Model', 'Body', 'Country', 'Condition', 'Fuel_Type',
       'Drivetrain', 'Gearbox', 'Color', 'Upholstery', 'Seller'],
      dtype='object')

In [36]:
for i in f1:
    f[i]=f[i].fillna(f[i].mode()[0])
    f[i]

In [37]:
f[f1].isnull().sum()

Make          0
Model         0
Body          0
Country       0
Condition     0
Fuel_Type     0
Drivetrain    0
Gearbox       0
Color         0
Upholstery    0
Seller        0
dtype: int64

In [38]:
f

,Make,Model,Body,Mileage_km,Price,Year,Country,Condition,Fuel_Type,Fuel_Consumption_l,...,Seats,Doors,Color,Upholstery,Full_Service_History,Non_Smoker_Vehicle,Previous_Owners,Seller,Car_age,price_perkm
0,Abarth,595,Compact,98000,16900,2020.0,IT,Used,Gasoline,6.7,...,4.0,3.0,White,Full leather,False,False,1.0,Dealer,6.0,0.172447
1,Abarth,595,Sedan,91500,12500,2017.0,IT,Used,Gasoline,6.0,...,4.0,3.0,Grey,Full leather,False,True,4.0,Dealer,9.0,0.136611
2,Abarth,595,Compact,40000,17990,2015.0,IT,Used,Gasoline,6.5,...,4.0,3.0,Bronze,Full leather,True,True,1.0,Dealer,11.0,0.449739
3,Abarth,500,Compact,133000,9300,2008.0,IT,Used,Gasoline,6.5,...,4.0,3.0,Black,Cloth,True,True,2.0,Dealer,18.0,0.069924
4,Abarth,595,Compact,61019,14990,2021.0,BE,Used,Gasoline,5.6,...,4.0,3.0,Yellow,Part leather,True,True,1.0,Dealer,5.0,0.245657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40489,Volvo,V60 Cross Country,Station wagon,73627,32990,2023.0,DE,Used,Diesel,5.6,...,5.0,5.0,Grey,Part leather,True,True,1.0,Dealer,3.0,0.448063
40490,Volvo,XC60,Off-Road/Pick-up,93671,26990,2020.0,IT,Used,Electric/Diesel,5.6,...,5.0,5.0,Grey,Cloth,False,False,1.0,Dealer,6.0,0.288133
40491,Volvo,V90,Station wagon,60200,32490,2020.0,DE,Used,Gasoline,5.6,...,5.0,5.0,Black,Full leather,True,True,2.0,Dealer,6.0,0.539692
40492,Volvo,XC40,Off-Road/Pick-up,49088,29450,2022.0,NL,Used,Electric/Gasoline,5.6,...,5.0,5.0,Black,Cloth,True,False,1.0,Dealer,4.0,0.599931
40493,Volvo,XC90,Off-Road/Pick-up,124750,43990,2022.0,DE,Used,Diesel,5.6,...,5.0,5.0,Grey,Full leather,True,True,2.0,Dealer,4.0,0.352622

In [15]:
d.isnull().sum()

Make                    0
Model                   0
Body                    0
Mileage_km              0
Price                   0
Year                    0
Country                 0
Condition               0
Fuel_Type               0
Fuel_Consumption_l      0
Drivetrain              0
Gearbox                 0
Gears                   0
Power_hp                0
Engine_Size_cc          0
Cylinders               0
Seats                   0
Doors                   0
Color                   0
Upholstery              0
Full_Service_History    0
Non_Smoker_Vehicle      0
Previous_Owners         0
Seller                  0
Car_age                 0
price_perkm             0
dtype: int64

In [16]:
from sklearn.preprocessing import LabelEncoder

In [39]:
d={}
le = LabelEncoder()
for i in f1:
    f[i] = le.fit_transform(f[i])
    d[i]=le

In [40]:
x=f.drop("Condition",axis=1)
y=f["Condition"]
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40494 entries, 0 to 40493
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Make                  40494 non-null  int64
 1   Model                 40494 non-null  int64
 2   Body                  40494 non-null  int64
 3   Mileage_km            40494 non-null  int64
 4   Price                 40494 non-null  int64
 5   Year                  40494 non-null  float64
 6   Country               40494 non-null  int64
 7   Fuel_Type             40494 non-null  int64
 8   Fuel_Consumption_l    40494 non-null  float64
 9   Drivetrain            40494 non-null  int64
 10  Gearbox               40494 non-null  int64
 11  Gears                 40494 non-null  float64
 12  Power_hp              40494 non-null  int64
 13  Engine_Size_cc        40494 non-null  float64
 14  Cylinders             40494 non-null  float64
 15  Seats                 40494 non-null  float64
 16  Doors                 40494 non-null  float64
 17  Color                 40494 non-null  int64
 18  Upholstery            40494 non-null  int64
 19  Full_Service_History  40494 non-null  bool
 20  Non_Smoker_Vehicle    40494 non-null  bool
 21  Previous_Owners       40494 non-null  float64
 22  Seller                40494 non-null  int64
 23  Car_age               40494 non-null  float64
 24  price_perkm           40494 non-null  float64
dtypes: bool(2), float64(10), int64(13)
memory usage: 7.2 MB

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
x_train,x_test,y_train,y_test = train_test_split(x,y, train_size=0.8,random_state=42)
x_train

,Make,Model,Body,Mileage_km,Price,Year,Country,Fuel_Type,Fuel_Consumption_l,Drivetrain,...,Seats,Doors,Color,Upholstery,Full_Service_History,Non_Smoker_Vehicle,Previous_Owners,Seller,Car_age,price_perkm
15617,17,671,5,49322,29900,2023.0,7,2,5.6,2,...,5.0,4.0,7,1,True,False,2.0,0,3.0,0.606208
35904,45,1239,2,114027,6490,2011.0,2,6,4.2,2,...,2.0,2.0,1,0,False,False,3.0,0,15.0,0.056916
17041,19,234,3,53219,15445,2023.0,2,6,5.6,1,...,5.0,5.0,12,1,True,True,1.0,0,3.0,0.290210
28661,32,903,3,93395,15450,2019.0,1,6,5.7,1,...,5.0,5.0,2,0,True,True,1.0,0,7.0,0.165425
24257,28,334,3,20,44690,2025.0,2,1,5.6,2,...,5.0,5.0,1,1,True,True,1.0,0,1.0,2128.095238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6265,5,1006,3,10,49950,2025.0,2,2,5.6,0,...,5.0,5.0,1,1,False,False,1.0,0,1.0,4540.909091
11284,12,463,3,118800,30900,2019.0,2,8,5.6,2,...,6.0,4.0,1,1,False,True,1.0,0,7.0,0.260099
38158,42,410,6,17300,27900,2024.0,5,4,5.6,1,...,5.0,5.0,2,2,False,False,1.0,0,2.0,1.612624
860,0,145,5,28689,22900,2020.0,5,6,6.8,1,...,4.0,3.0,7,3,False,False,1.0,0,6.0,0.798188
15795,17,977,3,26995,37990,2024.0,2,4,5.6,0,...,5.0,5.0,12,1,True,True,1.0,0,2.0,1.407246

In [43]:
from sklearn.ensemble import RandomForestClassifier

In [44]:
model = RandomForestClassifier(n_estimators=100,random_state=32,class_weight="balanced")
model.fit(x_train,y_train)

RandomForestClassifier(class_weight='balanced', random_state=32)

In [45]:
y_pred = model.predict(x_test)
y_pred

array([1, 1, 1, ..., 0, 1, 1], shape=(8099,))

In [46]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print("Accuracy Score:",accuracy_score(y_pred,y_test))

Accuracy Score: 0.9976540313618966

In [47]:
print("Report",confusion_matrix(y_pred,y_test))

Report [[ 362    1]
 [  18 7718]]

In [48]:
print("Report",classification_report(y_pred,y_test))

Report               precision    recall  f1-score   support

           0       0.95      1.00      0.97       363
           1       1.00      1.00      1.00      7736

    accuracy                           1.00      8099
   macro avg       0.98      1.00      0.99      8099
weighted avg       1.00      1.00      1.00      8099